### ISSUE TITLE
dns-shekan

### ISSUE THREAD

**Issue by mohmmadView** [BDadmehr0/DNS-403#1]
سلام دوست عزیز ممنون  از اسکریبت خوبتون  دی ان اس شکن سرعتش اومده پایین  ولی  ۴۰۳   عالیه ولی جدیدا    google .bard     شناسایش میکنه    و گیتهابم    به دی ان اس   حساس شده   راهکارتون چیه اسکریبت  که نوشته شده  زمانی که احتیاجی نیست از دی ان اس استفاده میکنه  یا نه  ممنون   باز از کار قشنگی که کردین

**Comment by BDadmehr0** [comment]
بله من متوجه این مشکل هستم که اکثر سرویس ها با دی ان اس **شکن** و **۴۰۳** به مشکل میخورند.
ولی این اسکریپت صرفا دی ان اس ها رو **ست** میکنه و کاری از من برنمیاد این مشکل رو باید به سرویس **۴۰۳** و دی ان اس **شکن** اطلاع بدید.
من یک گزینه دیگر در اسکریپت قرار دادم که دی ان اس سیستم رو به **۸.۸.۸.۸** تغییر میده برای مواقع که نیاز دارید دی ان اس **ریست** بشه

**Comment by mohmmadView** [comment]
خیلی عال متوجه شدم  ممنون عای بود کار جالب بود
